---
project_name: "mongodb"

mongodb_services:
  mongodb:
    container_name: mongodb
    group: mongodb
    enabled: true
    privileged: True
    image: "{{ mongodb_image_full }}"
    volumes:
      - "{{ node_config_directory }}/mongodb/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
      - "mongodb:/var/lib/mongodb"


####################
# Docker
####################
mongodb_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-mongodb"
mongodb_tag: "{{ openstack_release }}"
mongodb_image_full: "{{ mongodb_image }}:{{ mongodb_tag }}"


####################
# Mongodb
####################
mongodb_replication_set_name: "rs0"
