---
project_name: "kuryr"
libnetwork_project_name: "kuryr-libnetwork"

# NOTE(huikang, apuimedo): when you request a driver in a docker operation, such
# as docker network create, docker searches /usr/lib/docker or /etc/docker
# subdirs for network/storage plugin specs or json definitions. so it's either
# have ansible place the file there, or volume mount it and let the container
# place the file there

kuryr_services:
  kuryr:
    container_name: kuryr
    group: compute
    enabled: True
    image: "{{ kuryr_image_full }}"
    privileged: True
    cap_add:
      - NET_ADMIN
    volumes:
      - "{{ node_config_directory }}/kuryr/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/lib/modules:/lib/modules:ro"
      - "/run:/run:shared"
      - "/usr/lib/docker:/usr/lib/docker"
      - "{{ kolla_dev_repos_directory ~ '/kuryr/kuryr:/var/lib/kolla/venv/lib/python2.7/site-packages/kuryr' if kuryr_dev_mode | bool else '' }}"
      - "{{ kolla_dev_repos_directory ~ '/kuryr-libnetwork/kuryr_libnetwork:/var/lib/kolla/venv/lib/python2.7/site-packages/kuryr_libnetwork' if kuryr_dev_mode | bool else '' }}"
      - "kolla_logs:/var/log/kolla/"


####################
# Docker
####################
kuryr_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-kuryr-libnetwork"
kuryr_tag: "{{ openstack_release }}"
kuryr_image_full: "{{ kuryr_image }}:{{ kuryr_tag }}"


####################
# OpenStack
####################
kuryr_logging_debug: "{{ openstack_logging_debug }}"

kuryr_keystone_user: "kuryr"

openstack_kuryr_auth: "{{ openstack_auth }}"


####################
# Kolla
####################
kuryr_git_repository: "{{ kolla_dev_repos_git }}/{{ project_name }}"
kuryr_libnetwork_git_repository: "{{ kolla_dev_repos_git }}/{{ libnetwork_project_name }}"
kuryr_dev_repos_pull: "{{ kolla_dev_repos_pull }}"
kuryr_dev_mode: "{{ kolla_dev_mode }}"
