---
- name: Glance sanity check - create image
  kolla_toolbox:
    module_name: os_image
    module_args:
      auth: "{{ openstack_glance_auth }}"
      name: "glance_sanity_check"
      filename: "/etc/hostname"
      endpoint_type: "{{ openstack_interface }}"
  delegate_to: "{{ groups['glance-api'][0] }}"
  run_once: True
  register: img_create
  retries: 10
  delay: 3
  until: img_create | success
  when: kolla_enable_sanity_glance | bool

- name: Glance sanity check - cleanup
  kolla_toolbox:
    module_name: os_image
    module_args:
      auth: "{{ openstack_glance_auth }}"
      name: "glance_sanity_check"
      state: absent
      endpoint_type: "{{ openstack_interface }}"
  delegate_to: "{{ groups['glance-api'][0] }}"
  run_once: True
  when: kolla_enable_sanity_glance | bool
