---
- include: ceph.yml
  when:
    - enable_ceph | bool
    - glance_backend_ceph | bool

- include: external_ceph.yml
  when:
    - enable_ceph | bool == False
    - glance_backend_ceph | bool

- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ glance_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: glance_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/glance/"
      skip: true

- name: Set glance policy file
  set_fact:
    glance_policy_file: "{{ glance_policy.results.0.stat.path | basename }}"
    glance_policy_file_path: "{{ glance_policy.results.0.stat.path }}"
  when:
    - glance_policy.results

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: glance_config_jsons
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ glance_services }}"
  notify:
    - Restart glance-api container
    - Restart glance-registry container

- name: Copying over glance-*.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/{{ item.key }}.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/glance.conf"
      - "{{ node_custom_config }}/glance/{{ item.key }}.conf"
      - "{{ node_custom_config }}/glance/{{ inventory_hostname }}/{{ item.key }}.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ item.key }}.conf"
    mode: "0660"
  become: true
  register: glance_confs
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ glance_services }}"
  notify:
    - Restart glance-api container
    - Restart glance-registry container

- name: Copying over glance-swift.conf for glance_api
  vars:
    glance_api: "{{ glance_services['glance-api'] }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/glance-swift.conf.j2"
      - "{{ node_custom_config }}/glance-swift.conf"
      - "{{ node_custom_config }}/glance/glance-swift.conf"
      - "{{ node_custom_config }}/glance/{{ inventory_hostname }}/glance-swift.conf"
    dest: "{{ node_config_directory }}/glance-api/glance-swift.conf"
    mode: "0660"
  become: true
  register: glance_swift_conf
  when:
    - glance_api.enabled | bool
    - inventory_hostname in groups[glance_api.group]
    - glance_backend_swift | bool
  notify:
    - Restart glance-api container

- name: Copying over existing policy file
  template:
    src: "{{ glance_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ glance_policy_file }}"
    mode: "0660"
  become: true
  register: glance_policy_overwriting
  when:
    - glance_policy_file is defined
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ glance_services }}"
  notify:
    - Restart glance-api container
    - Restart glance-registry container

- name: Check glance containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  register: check_glance_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ glance_services }}"
  notify:
    - Restart glance-api container
    - Restart glance-registry container
