---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
    recurse: yes
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ zookeeper_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: zookeeper_config_jsons
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ zookeeper_services }}"
  notify:
    - Restart zookeeper container

- name: Copying over zookeeper configuration
  merge_configs:
    sources:
      - "{{ role_path }}/templates/{{ item.key }}.cfg.j2"
      - "{{ node_custom_config }}/{{ item.key }}.cfg"
      - "{{ node_custom_config }}/{{ item.key }}/{{ inventory_hostname }}/{{ item.key }}.cfg"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ item.key }}.cfg"
    mode: "0660"
  become: true
  register: zookeeper_confs
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ zookeeper_services }}"
  notify:
    - Restart zookeeper container

- name: Copying over zookeeper instance id
  template:
    src: "myid.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/myid"
    mode: "0660"
  become: true
  register: zookeeper_instance_id
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ zookeeper_services }}"
  notify:
    - Restart zookeeper container

- name: Check zookeeper containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    environment: "{{ item.value.environment }}"
  register: check_zookeeper_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ zookeeper_services }}"
  notify:
    - Restart zookeeper container
