---
project_name: "octavia"

octavia_services:
  octavia-api:
    container_name: octavia_api
    group: octavia-api
    enabled: true
    image: "{{ octavia_api_image_full }}"
    volumes:
      - "{{ node_config_directory }}/octavia-api/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  octavia-health-manager:
    container_name: octavia_health_manager
    group: octavia-health-manager
    enabled: true
    image: "{{ octavia_health_manager_image_full }}"
    volumes:
      - "{{ node_config_directory }}/octavia-health-manager/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  octavia-housekeeping:
    container_name: octavia_housekeeping
    group: octavia-housekeeping
    enabled: true
    image: "{{ octavia_housekeeping_image_full }}"
    volumes:
      - "{{ node_config_directory }}/octavia-housekeeping/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  octavia-worker:
    container_name: octavia_worker
    group: octavia-worker
    enabled: true
    image: "{{ octavia_worker_image_full }}"
    volumes:
      - "{{ node_config_directory }}/octavia-worker/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"

octavia_required_roles:
  - load-balancer_observer
  - load-balancer_global_observer
  - load-balancer_member
  - load-balancer_admin
  - load-balancer_quota_admin


####################
# Database
####################
octavia_database_name: "octavia"
octavia_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}octavia{% endif %}"
octavia_database_address: "{{ database_address }}:{{ database_port }}"


####################
# Docker
####################
octavia_install_type: "{{ kolla_install_type }}"
octavia_tag: "{{ openstack_release }}"

octavia_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ octavia_install_type }}-octavia-api"
octavia_api_tag: "{{ octavia_tag }}"
octavia_api_image_full: "{{ octavia_api_image }}:{{ octavia_api_tag }}"

octavia_health_manager_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ octavia_install_type }}-octavia-health-manager"
octavia_health_manager_tag: "{{ octavia_tag }}"
octavia_health_manager_image_full: "{{ octavia_health_manager_image }}:{{ octavia_health_manager_tag }}"

octavia_housekeeping_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ octavia_install_type }}-octavia-housekeeping"
octavia_housekeeping_tag: "{{ octavia_tag }}"
octavia_housekeeping_image_full: "{{ octavia_housekeeping_image }}:{{ octavia_housekeeping_tag }}"

octavia_worker_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ octavia_install_type }}-octavia-worker"
octavia_worker_tag: "{{ octavia_tag }}"
octavia_worker_image_full: "{{ octavia_worker_image }}:{{ octavia_worker_tag }}"


####################
# OpenStack
####################
octavia_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ octavia_api_port }}"
octavia_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn }}:{{ octavia_api_port }}"
octavia_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn }}:{{ octavia_api_port }}"

octavia_logging_debug: "{{ openstack_logging_debug }}"

octavia_keystone_user: "octavia"

openstack_octavia_auth: "{{ openstack_auth }}"
