---
- name: Get container facts
  kolla_container_facts:
    name:
      - ceph_rgw
  register: container_facts

- name: Checking free port for RadosGW
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ rgw_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['ceph_rgw'] is not defined
    - inventory_hostname in groups['ceph-rgw']

- name: Check whether the Swift service is enabled
  local_action: fail msg='Ceph-rgw conflicts with Swift, and so you should only enable one of them'
  when: enable_swift | bool and enable_ceph_rgw | bool
  run_once: True
