---
- name: Pulling ceph-mon image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ ceph_mon_image_full }}"
  when: inventory_hostname in groups['ceph-mon']

- name: Pulling ceph-osd image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ ceph_osd_image_full }}"
  when: inventory_hostname in groups['ceph-osd']

- name: Pulling ceph-rgw image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ ceph_rgw_image_full }}"
  when: inventory_hostname in groups['ceph-rgw']

- name: Pulling ceph-mgr image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ ceph_mgr_image_full }}"
  when:
    - inventory_hostname in groups['ceph-mgr']

- name: Pulling ceph-mds image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ ceph_mds_image_full }}"
  when:
    - enable_ceph_mds | bool
    - inventory_hostname in groups['ceph-mds']

- name: Pulling ceph-nfs image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ ceph_nfs_image_full }}"
  when:
    - enable_ceph_nfs | bool
    - inventory_hostname in groups['ceph-nfs']
