---
- name: Starting ceph-nfs container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ ceph_nfs_image_full }}"
    name: "ceph_nfs"
    volumes:
      - "{{ node_config_directory }}/ceph-nfs/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/dbus:/var/run/dbus"
      - "kolla_logs:/var/log/kolla/"
