---
- include: config.yml

# NOTE(jeffrey4l): client.admin caps should be update when upgrade from Jewel
# to Luminous
- name: configuring client.admin caps
  kolla_ceph_keyring:
    name: client.admin
    caps: "{{ ceph_client_admin_keyring_caps }}"
  run_once: True
  delegate_to: "{{ groups['ceph-mon'][0] }}"

- include: start_mons.yml
  when: inventory_hostname in groups['ceph-mon']

- include: start_mgrs.yml
  when: inventory_hostname in groups['ceph-mgr']

- include: start_osds.yml
  when: inventory_hostname in groups['ceph-osd']

- include: start_rgws.yml
  when:
    - enable_ceph_rgw | bool
    - inventory_hostname in groups['ceph-rgw']

- include: start_mdss.yml
  when:
    - enable_ceph_mds | bool
    - inventory_hostname in groups['ceph-mds']

- include: start_nfss.yml
  when:
    - enable_ceph_nfs | bool
    - inventory_hostname in groups['ceph-nfs']
