---
- include: config.yml

- include: clone.yml
  when:
    - horizon_dev_mode | bool

- include: bootstrap_service.yml
  when: horizon_backend_database | bool

- name: Flush handlers
  meta: flush_handlers
