---
- include: port_checks.yml
  when:
    - inventory_hostname not in groups['deployment']

- include: service_checks.yml

- include: package_checks.yml

- include: user_checks.yml

- include: database_checks.yml
