---
project_name: "freezer"

freezer_services:
  freezer-api:
    container_name: freezer_api
    group: freezer-api
    enabled: true
    image: "{{ freezer_api_image_full }}"
    volumes:
      - "{{ node_config_directory }}/freezer-api/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "freezer:/var/lib/freezer/"
      - "kolla_logs:/var/log/kolla/"
  freezer-scheduler:
    container_name: freezer_scheduler
    group: freezer-scheduler
    enabled: true
    image: "{{ freezer_scheduler_image_full }}"
    volumes:
      - "{{ node_config_directory }}/freezer-scheduler/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "freezer:/var/lib/freezer/"
      - "kolla_logs:/var/log/kolla/"


####################
# Docker
####################
freezer_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-freezer-api"
freezer_api_tag: "{{ openstack_release }}"
freezer_api_image_full: "{{ freezer_api_image }}:{{ freezer_api_tag }}"
freezer_scheduler_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-freezer-scheduler"
freezer_scheduler_tag: "{{ openstack_release }}"
freezer_scheduler_image_full: "{{ freezer_scheduler_image }}:{{ freezer_scheduler_tag }}"


####################
# OpenStack
####################
freezer_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ freezer_api_port }}"
freezer_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn }}:{{ freezer_api_port }}"
freezer_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn }}:{{ freezer_api_port }}"

freezer_logging_debug: "{{ openstack_logging_debug }}"

freezer_keystone_user: "freezer"

openstack_freezer_auth: "{{ openstack_auth }}"
