---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when: inventory_hostname in groups['compute']
  with_items:
    - "multipathd"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
    mode: "0660"
  become: true
  when: inventory_hostname in groups['compute']
  with_items:
    - "multipathd"

- name: Copying over multipath.conf
  template:
    src: "{{ role_path }}/templates/multipath.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}/multipath.conf"
    mode: "0660"
  become: true
  with_items:
    - "multipathd"
