---
- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ openvswitch_services }}"

- name: Copying over config.json files for services
  become: true
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0770"
  register: openvswitch_config_jsons
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ openvswitch_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over start-ovs file for openvswitch-vswitchd
  become: true
  vars:
    service: "{{ openvswitch_services['openvswitch-vswitchd'] }}"
  template:
    src: "{{ role_path }}/templates/start-ovs.j2"
    dest: "{{ node_config_directory }}/openvswitch-vswitchd/start-ovs"
  register: openvswitch_start_ovs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - "Restart openvswitch-vswitchd container"

- name: Copying over start-ovsdb-server files for openvswitch-db-server
  become: true
  vars:
    service: "{{ openvswitch_services['openvswitch-db-server'] }}"
  template:
    src: "{{ role_path }}/templates/start-ovsdb-server.j2"
    dest: "{{ node_config_directory }}/openvswitch-db-server/start-ovsdb-server"
  register: openvswitch_start_ovsdb_server
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - "Restart openvswitch-db-server container"

- name: Check openvswitch containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    volumes: "{{ item.value.volumes }}"
  register: check_openvswitch_containers
  when:
    - action != "config"
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ openvswitch_services }}"
  notify:
    - "Restart {{ item.key }} container"
