---
- include: register.yml
  when: enable_keystone | bool and
        (inventory_hostname in groups['ironic-api'] or
        inventory_hostname in groups['ironic-inspector'])

- include: config.yml

- include: bootstrap_service.yml

- name: Flush handlers
  meta: flush_handlers
