---
- name: Setting sysctl values
  become: true
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes
  with_items:
    - { name: "vm.max_map_count", value: 262144}
  when:
    - set_sysctl | bool
    - inventory_hostname in groups['elasticsearch']

- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ elasticsearch_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: elasticsearch_config_jsons
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ elasticsearch_services }}"
  notify:
    - Restart elasticsearch container

- name: Copying over elasticsearch.yml
  template:
    src: "elasticsearch.yml.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ item.key }}.yml"
    mode: "0660"
  become: true
  register: elasticsearch_confs
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ elasticsearch_services }}"
  notify:
    - Restart elasticsearch container

- name: Check elasticsearch containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    environment: "{{ item.value.environment }}"
  register: check_elasticsearch_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ elasticsearch_services }}"
  notify:
    - Restart elasticsearch container
