---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ watcher_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: watcher_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/watcher/"
      skip: true

- name: Set watcher policy file
  set_fact:
    watcher_policy_file: "{{ watcher_policy.results.0.stat.path | basename }}"
    watcher_policy_file_path: "{{ watcher_policy.results.0.stat.path }}"
  when:
    - watcher_policy.results

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  register: watcher_config_jsons
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ watcher_services }}"
  notify:
    - Restart watcher-api container
    - Restart watcher-engine container
    - Restart watcher-applier container

- name: Copying over watcher.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/watcher.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/watcher.conf"
      - "{{ node_custom_config }}/watcher/{{ item.key }}.conf"
      - "{{ node_custom_config }}/watcher/{{ inventory_hostname }}/watcher.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/watcher.conf"
    mode: "0660"
  register: watcher_confs
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ watcher_services }}"
  notify:
    - Restart watcher-api container
    - Restart watcher-engine container
    - Restart watcher-applier container

- name: Copying over existing policy file
  template:
    src: "{{ watcher_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ watcher_policy_file }}"
  register: watcher_policy_overwriting
  when:
    - watcher_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ watcher_services }}"
  notify:
    - Restart watcher-api container
    - Restart watcher-applier container
    - Restart watcher-engine container

- name: Check watcher containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  register: check_watcher_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ watcher_services }}"
  notify:
    - Restart watcher-api container
    - Restart watcher-applier container
    - Restart watcher-engine container
