---
# NOTE (duonghq): I break pull and config into 2 phases to prevent new version
# of service start if node or process in node crash accidentally.
- include: pull.yml
  when: inventory_hostname == groups["cinder-api"][0]

- include: config.yml
  when: inventory_hostname == groups["cinder-api"][0]

- include: bootstrap_service.yml

- include: pull.yml

- include: config.yml

- name: Flush handlers
  meta: flush_handlers

- name: Running Cinder online schema migration
  vars:
    cinder_api: "{{ cinder_services['cinder-api'] }}"
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    detach: False
    environment:
      KOLLA_OSM:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      MAX_NUMBER: "{{ cinder_max_number_osm | default(10) }}"
    image: "{{ cinder_api.image }}"
    labels:
      BOOTSTRAP:
    name: "bootstrap_cinder"
    restart_policy: "never"
    volumes: "{{ cinder_api.volumes }}"
  run_once: True
  delegate_to: "{{ groups[cinder_api.group][0] }}"
