---
- name: Creating the Octavia service and endpoint
  kolla_toolbox:
    module_name: "kolla_keystone_service"
    module_args:
      service_name: "octavia"
      service_type: "load-balancer"
      description: "Octavia Load Balancing Service"
      endpoint_region: "{{ openstack_region_name }}"
      url: "{{ item.url }}"
      interface: "{{ item.interface }}"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ '{{ openstack_octavia_auth }}' }}"
      endpoint_type: "{{ openstack_interface }}"
    module_extra_vars:
      openstack_octavia_auth: "{{ openstack_octavia_auth }}"
  run_once: True
  with_items:
    - {'interface': 'admin', 'url': '{{ octavia_admin_endpoint }}'}
    - {'interface': 'internal', 'url': '{{ octavia_internal_endpoint }}'}
    - {'interface': 'public', 'url': '{{ octavia_public_endpoint }}'}

- name: Creating the Octavia project, user, and role
  kolla_toolbox:
    module_name: "kolla_keystone_user"
    module_args:
      project: "service"
      user: "{{ octavia_keystone_user }}"
      password: "{{ octavia_keystone_password }}"
      role: "admin"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ '{{ openstack_octavia_auth }}' }}"
      endpoint_type: "{{ openstack_interface }}"
    module_extra_vars:
      openstack_octavia_auth: "{{ openstack_octavia_auth }}"
  run_once: True

- name: Adding octavia user into admin project
  kolla_toolbox:
    module_name: "os_user_role"
    module_args:
      user: "{{ octavia_keystone_user }}"
      role: admin
      project: admin
      auth: "{{ '{{ openstack_octavia_auth }}' }}"
      endpoint_type: "{{ openstack_interface }}"
    module_extra_vars:
      openstack_octavia_auth: "{{ openstack_octavia_auth }}"
  run_once: True

- name: Adding octavia related roles
  kolla_toolbox:
    module_name: "os_keystone_role"
    module_args:
      name: "{{ item }}"
      auth: "{{ '{{ openstack_octavia_auth }}' }}"
      endpoint_type: "{{ openstack_interface }}"
    module_extra_vars:
      openstack_octavia_auth: "{{ openstack_octavia_auth }}"
  run_once: True
  with_items: "{{ octavia_required_roles }}"
