---
- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/manila-share"
    state: "directory"
  when:
    - inventory_hostname in groups['manila-share']

- name: Copying over ceph.conf for manila
  merge_configs:
    sources:
      - "{{ node_custom_config }}/manila/ceph.conf"
      - "{{ node_custom_config }}/manila/manila-share/ceph.conf"
    dest: "{{ node_config_directory }}/manila-share/ceph.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups['manila-share']
  notify:
    - Restart manila-share container

- name: Copy over Ceph keyring files for manila
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/manila-share/"
    mode: "0600"
  become: true
  with_fileglob:
    - "{{ node_custom_config }}/manila/ceph.client.manila.keyring"
    - "{{ node_custom_config }}/manila/manila/ceph.client.manila.keyring"
  when:
    - inventory_hostname in groups['manila-share']
  notify:
    - Restart manila-share container

- name: Ensuring config directory has correct owner and permission
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    recurse: yes
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  when: inventory_hostname in groups[item]
  with_items:
    - "manila-share"
