---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ blazar_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: blazar_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/blazar/"
      skip: true

- name: Set blazar policy file
  set_fact:
    blazar_policy_file: "{{ blazar_policy.results.0.stat.path | basename }}"
    blazar_policy_file_path: "{{ blazar_policy.results.0.stat.path }}"
  when:
    - blazar_policy.results

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: blazar_config_jsons
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ blazar_services }}"
  notify:
    - Restart blazar-api container
    - Restart blazar-manager container

- name: Copying over blazar.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/blazar.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/blazar.conf"
      - "{{ node_custom_config }}/blazar/{{ item.key }}.conf"
      - "{{ node_custom_config }}/blazar/{{ inventory_hostname }}/blazar.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/blazar.conf"
    mode: "0660"
  become: true
  register: blazar_confs
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ blazar_services }}"
  notify:
    - Restart blazar-api container
    - Restart blazar-manager container

- name: Copying over existing policy file
  template:
    src: "{{ blazar_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ blazar_policy_file }}"
    mode: "0660"
  become: true
  register: blazar_policy_overwriting
  when:
    - blazar_policy_file is defined
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ blazar_services }}"
  notify:
    - Restart blazar-api container
    - Restart blazar-manager container

- name: Check blazar containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  register: check_blazar_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ blazar_services }}"
  notify:
    - Restart blazar-api container
    - Restart blazar-manager container
