---
- include: register.yml
  when: inventory_hostname in groups['blazar-api']

- include: config.yml
  when: inventory_hostname in groups['blazar-api'] or
        inventory_hostname in groups['blazar-manager']

- include: bootstrap.yml
  when: inventory_hostname in groups['blazar-api']

- name: Flush handlers
  meta: flush_handlers
