---
- name: Get container facts
  kolla_container_facts:
    name:
      - blazar_api
  register: container_facts

- name: Checking free port for blazar API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ blazar_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['blazar_api'] is not defined
    - inventory_hostname in groups['blazar-api']
