---
project_name: "senlin"

senlin_services:
  senlin-api:
    container_name: senlin_api
    group: senlin-api
    enabled: true
    image: "{{ senlin_api_image_full }}"
    volumes:
      - "{{ node_config_directory }}/senlin-api/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  senlin-engine:
    container_name: senlin_engine
    group: senlin-engine
    enabled: true
    image: "{{ senlin_engine_image_full }}"
    volumes:
      - "{{ node_config_directory }}/senlin-engine/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"

####################
# Database
####################
senlin_database_name: "senlin"
senlin_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}senlin{% endif %}"
senlin_database_address: "{{ database_address }}:{{ database_port }}"


####################
# Docker
####################
senlin_install_type: "{{ kolla_install_type }}"
senlin_tag: "{{ openstack_release }}"

senlin_engine_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ senlin_install_type }}-senlin-engine"
senlin_engine_tag: "{{ senlin_tag }}"
senlin_engine_image_full: "{{ senlin_engine_image }}:{{ senlin_engine_tag }}"

senlin_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ senlin_install_type }}-senlin-api"
senlin_api_tag: "{{ senlin_tag }}"
senlin_api_image_full: "{{ senlin_api_image }}:{{ senlin_api_tag }}"


####################
# OpenStack
####################
senlin_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ senlin_api_port }}"
senlin_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn }}:{{ senlin_api_port }}"
senlin_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn }}:{{ senlin_api_port }}"

senlin_logging_debug: "{{ openstack_logging_debug }}"

senlin_keystone_user: "senlin"

openstack_senlin_auth: "{{ openstack_auth }}"
