---
project_name: "magnum"

magnum_services:
  magnum-api:
    container_name: magnum_api
    group: magnum-api
    enabled: true
    image: "{{ magnum_api_image_full }}"
    environment:
      DUMMY_ENVIRONMENT: kolla_useless_env
    volumes:
      - "{{ node_config_directory }}/magnum-api/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ kolla_dev_repos_directory ~ '/magnum/magnum:/var/lib/kolla/venv/lib/python2.7/site-packages/magnum' if magnum_dev_mode | bool else '' }}"
      - "kolla_logs:/var/log/kolla/"
  magnum-conductor:
    container_name: magnum_conductor
    group: magnum-conductor
    enabled: true
    image: "{{ magnum_conductor_image_full }}"
    environment: "{{ container_proxy }}"
    volumes:
      - "{{ node_config_directory }}/magnum-conductor/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "magnum:/var/lib/magnum/"
      - "{{ kolla_dev_repos_directory ~ '/magnum/magnum:/var/lib/kolla/venv/lib/python2.7/site-packages/magnum' if magnum_dev_mode | bool else '' }}"
      - "kolla_logs:/var/log/kolla/"


####################
# Database
####################
magnum_database_name: "magnum"
magnum_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}magnum{% endif %}"
magnum_database_address: "{{ database_address }}:{{ database_port }}"


####################
# Magnum
####################
enable_cluster_user_trust: False


####################
# Docker
####################
magnum_install_type: "{{ kolla_install_type }}"
magnum_tag: "{{ openstack_release }}"

magnum_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ magnum_install_type }}-magnum-api"
magnum_api_tag: "{{ magnum_tag }}"
magnum_api_image_full: "{{ magnum_api_image }}:{{ magnum_api_tag }}"

magnum_conductor_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ magnum_install_type }}-magnum-conductor"
magnum_conductor_tag: "{{ magnum_tag }}"
magnum_conductor_image_full: "{{ magnum_conductor_image }}:{{ magnum_conductor_tag }}"


####################
# OpenStack
####################
magnum_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ magnum_api_port }}/v1"
magnum_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn }}:{{ magnum_api_port }}/v1"
magnum_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn }}:{{ magnum_api_port }}/v1"

magnum_logging_debug: "{{ openstack_logging_debug }}"

magnum_keystone_user: "magnum"
magnum_trustee_domain_admin: "magnum_trustee_domain_admin"
magnum_trustee_domain: "magnum"

openstack_magnum_auth: "{{ openstack_auth }}"


####################
# Kolla
####################
magnum_git_repository: "{{ kolla_dev_repos_git }}/{{ project_name }}"
magnum_dev_repos_pull: "{{ kolla_dev_repos_pull }}"
magnum_dev_mode: "{{ kolla_dev_mode }}"
