---
- hosts: all
  become: true

  tasks:
  - name: Ensure /etc/hostname is valid for SELinux
    command: restorecon -v /etc/hostname
    when: ansible_os_family == 'RedHat'

  - name: Install wget package
    package: name=wget

  - name: Add sudo group
    group:
      name: sudo
      state: present

  - name: Allow 'sudo' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      line: "%sudo ALL=(ALL) NOPASSWD: ALL"

  - name: Add jenkins to sudo group
    user:
      name: jenkins
      append: yes
      groups: "sudo"


- hosts: all
  become: true

  tasks:
    - name: Create log directory for node
      file:
        state: directory
        path: /tmp/{{ inventory_hostname }}
      become: false
