---
- name: Starting bifrost deploy container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ bifrost_deploy_image_full }}"
    name: "bifrost_deploy"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/bifrost/:/etc/bifrost:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev:/dev"
      - "kolla_logs:/var/log/kolla/"
      - "bifrost_httpboot:/httpboot/"
      - "bifrost_ironic:/var/lib/ironic/"
      - "bifrost_mariadb:/var/lib/mysql/"
      - "bifrost_rabbitmq:/var/lib/rabbitmq/"
      - "bifrost_tftpboot:/tftpboot/"
