---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ senlin_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: senlin_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/senlin/"
      skip: true

- name: Set senlin policy file
  set_fact:
    senlin_policy_file: "{{ senlin_policy.results.0.stat.path | basename }}"
    senlin_policy_file_path: "{{ senlin_policy.results.0.stat.path }}"
  when:
    - senlin_policy.results

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: senlin_config_jsons
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ senlin_services }}"
  notify:
    - Restart senlin-api container
    - Restart senlin-engine container

- name: Copying over senlin.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/senlin.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/senlin.conf"
      - "{{ node_custom_config }}/senlin/{{ item.key }}.conf"
      - "{{ node_custom_config }}/senlin/{{ inventory_hostname }}/senlin.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/senlin.conf"
    mode: "0660"
  become: true
  register: senlin_confs
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ senlin_services }}"
  notify:
    - Restart senlin-api container
    - Restart senlin-engine container

- name: Copying over existing policy file
  template:
    src: "{{ senlin_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ senlin_policy_file }}"
    mode: "0660"
  become: true
  register: senlin_policy_overwriting
  when:
    - senlin_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ senlin_services }}"
  notify:
    - Restart senlin-api container
    - Restart senlin-engine container

- name: Check senlin containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  register: check_senlin_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ senlin_services }}"
  notify:
    - Restart senlin-api container
    - Restart senlin-engine container
