---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sahara_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: sahara_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/sahara/"
      skip: true

- name: Set sahara policy file
  set_fact:
    sahara_policy_file: "{{ sahara_policy.results.0.stat.path | basename }}"
    sahara_policy_file_path: "{{ sahara_policy.results.0.stat.path }}"
  when:
    - sahara_policy.results

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: sahara_config_jsons
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sahara_services }}"
  notify:
    - Restart sahara-api container
    - Restart sahara-engine container

- name: Copying over sahara.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/sahara.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/sahara.conf"
      - "{{ node_custom_config }}/sahara/{{ item.key }}.conf"
      - "{{ node_custom_config }}/sahara/{{ inventory_hostname }}/sahara.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/sahara.conf"
    mode: "0660"
  become: true
  register: sahara_confs
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sahara_services }}"
  notify:
    - Restart sahara-api container
    - Restart sahara-engine container

- name: Copying over existing policy file
  template:
    src: "{{ sahara_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ sahara_policy_file }}"
    mode: "0660"
  become: true
  register: sahara_policy_overwriting
  when:
    - sahara_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sahara_services }}"
  notify:
    - Restart sahara-api container
    - Restart sahara-engine container

- name: Check sahara containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    volumes: "{{ item.value.volumes }}"
  register: check_sahara_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sahara_services }}"
  notify:
    - Restart sahara-api container
    - Restart sahara-engine container
