---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    recurse: yes
    mode: "0770"
  become: true
  when: inventory_hostname in groups[item.value.group]
  with_dict: "{{ mistral_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: mistral_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/mistral/"
      skip: true

- name: Set mistral policy file
  set_fact:
    mistral_policy_file: "{{ mistral_policy.results.0.stat.path | basename }}"
    mistral_policy_file_path: "{{ mistral_policy.results.0.stat.path }}"
  when:
    - mistral_policy.results

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: mistral_config_jsons
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ mistral_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over mistral.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/mistral.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/mistral.conf"
      - "{{ node_custom_config }}/mistral/{{ item.key }}.conf"
      - "{{ node_custom_config }}/mistral/{{ inventory_hostname }}/mistral.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/mistral.conf"
    mode: "0660"
  become: true
  register: mistral_confs
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ mistral_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over existing policy file
  template:
    src: "{{ mistral_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ mistral_policy_file }}"
    mode: "0660"
  become: true
  register: mistral_policy_overwriting
  when:
    - mistral_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ mistral_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Check mistral containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  register: check_mistral_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ mistral_services }}"
  notify:
    - Restart {{ item.key }} container
