---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ designate_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: designate_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/designate/"
      skip: true

- name: Set designate policy file
  set_fact:
    designate_policy_file: "{{ designate_policy.results.0.stat.path | basename }}"
    designate_policy_file_path: "{{ designate_policy.results.0.stat.path }}"
  when:
    - designate_policy.results

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: designate_config_jsons
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ designate_services }}"
  notify:
    - Restart designate-api container
    - Restart designate-central container
    - Restart designate-producer container
    - Restart designate-mdns container
    - Restart designate-sink container
    - Restart designate-backend-bind9 container
    - Restart designate-worker container

- name: Copying over designate.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/designate.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/designate.conf"
      - "{{ node_custom_config }}/designate/{{ item.key }}.conf"
      - "{{ node_custom_config }}/designate/{{ inventory_hostname }}/designate.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/designate.conf"
    mode: "0660"
  become: true
  register: designate_confs
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ designate_services }}"
  notify:
    - Restart designate-api container
    - Restart designate-central container
    - Restart designate-producer container
    - Restart designate-mdns container
    - Restart designate-sink container
    - Restart designate-worker container

- name: Copying over pools.yaml
  vars:
    service: "{{ designate_services['designate-worker'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/designate-worker/pools.yaml"
    mode: "0660"
  become: true
  register: designate_pool
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/designate/pools.yaml"
    - "{{ role_path }}/templates/pools.yaml.j2"
  notify:
    - Restart designate-worker container

- name: Copying over named.conf
  vars:
    service: "{{ designate_services['designate-backend-bind9'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/designate-backend-bind9/named.conf"
    mode: "0660"
  become: true
  register: designate_named
  when:
    - designate_backend == 'bind9'
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/designate/designate-backend-bind9/{{ inventory_hostname }}/named.conf"
    - "{{ node_custom_config }}/designate/designate-backend-bind9/named.conf"
    - "{{ node_custom_config }}/designate/named.conf"
    - "{{ role_path }}/templates/named.conf.j2"
  notify:
    - Restart designate-backend-bind9 container

- name: Copying over rndc.conf
  template:
    src: "rndc.conf.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/rndc.conf"
    mode: "0660"
  become: true
  register: designate_rndc_conf
  when:
    - designate_backend == 'bind9' and designate_backend_external == 'no'
    - item.key in [ "designate-backend-bind9", "designate-worker" ]
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ designate_services }}"
  notify:
    - Restart designate-backend-bind9 container
    - Restart designate-worker container

- name: Copying over rndc.key
  template:
    src: "rndc.key.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/rndc.key"
    mode: "0660"
  become: true
  register: designate_rndc_key_file
  when:
    - designate_backend == 'bind9' and designate_backend_external == 'no'
    - item.key in [ "designate-backend-bind9", "designate-worker" ]
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ designate_services }}"
  notify:
    - Restart designate-backend-bind9 container
    - Restart designate-worker container

- include: backend_external.yml
  when: designate_backend_external == 'bind9'

- name: Check if policies shall be overwritten
  local_action: stat path="{{ node_custom_config }}/designate/policy.json"
  run_once: True
  register: designate_policy

- name: Copying over existing policy file
  template:
    src: "{{ designate_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ designate_policy_file }}"
    mode: "0770"
  become: true
  register: designate_policy_overwriting
  when:
    - designate_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ designate_services }}"
  notify:
    - Restart designate-api container
    - Restart designate-central container
    - Restart designate-producer container
    - Restart designate-mdns container
    - Restart designate-sink container
    - Restart designate-worker container

- name: Check designate containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  register: check_designate_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ designate_services }}"
  notify:
    - Restart designate-api container
    - Restart designate-central container
    - Restart designate-producer container
    - Restart designate-mdns container
    - Restart designate-sink container
    - Restart designate-backend-bind9 container
    - Restart designate-worker container
